### ISSUE TITLE
GitHub auth fails

### ISSUE THREAD

**Issue by matthewkmayer** [gomicro/train#30]
Train version v0.1.1.

I ran `train auth`, allowed access to the orgs I'd like, then the console output said `Error: Failed to read config file: open /Users/matthew/.train/config: no such file or directory` .

No folder or file was created in that spot.

Perhaps train can create the folder and file if not already present.

**Comment by dan9186** [comment]
Confirmed fixed in [v0.1.2](https://github.com/gomicro/train/releases/tag/v0.1.2)

**Comment by matthewkmayer** [comment]
I'm seeing the same error with train 0.1.2. The app is already authed with GitHub so `train auth` opened a page stating `Config file updated, you can close this window.` without asking for permissions, as I expected. However the error still occurred:

```bash
$ ~/Downloads/train auth
Error: config: write file: open /Users/matthew/.train/config: no such file or directory
```

```bash
$ ~/Downloads/train version
Train version v0.1.2
```

**Comment by dan9186** [comment]
Can you try creating the directory for `/Users/matthew/.train` to see if it solves the problem. Thinking on it, I didn't do anything to make sure the directory exists, only the file.

**Comment by matthewkmayer** [comment]
Creating the directory allows train to work as expected.

What do you think about creating the directory if it doesn't exist?

**Comment by dan9186** [comment]
Cool, that's what I was hoping the fix was. I will add creating the directory. I just didn't think about it at 1 AM.

**Comment by dan9186** [comment]
The directory creation should now be fixed with v0.1.3
